name: Project-4-Workflow
on:
  push:
    branches: main
    #workflows-dispatch:
    #tags:
    #  - "v*.*.*"
env:
  DOCKER_HUB_REPO: mjzimmer121999/zimmer-ceg3120
jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: If login fails, files can be viewed
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          #platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zimmer-ceg3120:latest
          push: true